# Generated by Django 3.2.8 on 2023-04-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('memo', models.CharField(max_length=100)),
                ('money', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
